name: Trigger auto deployment for weather-app-4

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/weather-app-4-AutoDeployTrigger-d76d034d-b067-4273-bf78-fca946c332b1.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: k8sacr4.azurecr.io
          username: ${{ secrets.WEATHERAPP4_REGISTRY_USERNAME }}
          password: ${{ secrets.WEATHERAPP4_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: k8sacr4.azurecr.io/weather-app-4:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WEATHERAPP4_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n weather-app-4 -g DefaultResourceGroup-CCA --server k8sacr4.azurecr.io --username  ${{ secrets.WEATHERAPP4_REGISTRY_USERNAME }} --password ${{ secrets.WEATHERAPP4_REGISTRY_PASSWORD }}
            az containerapp update -n weather-app-4 -g DefaultResourceGroup-CCA --image k8sacr4.azurecr.io/weather-app-4:${{ github.sha }}
